defaults:
  - _self_
  - models: gpt4_turbo_2024_03
  - evaluation: query_splits

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
